### PR TITLE
Updated Unit Tests

### PR DESCRIPTION
**Pull request by Zunaira1989**

### CODE REVIEW

**Comment by fujaidesu** [comment]
Hi, I am checking your pull request. But I found there are some bugs in the code so it cannot be executed.

And also it seems that you have added quite a lot of new unit test cases. I don't know whether the test document is also required to be changed or not. Please discuss with Tolga as this may costs a lot of time.

In my opinion, I think it is enough to just update the function name in the previous program without adding new unit tests. If you are unsure, please do post your thought in the dicussion forum.

**Comment by Zunaira1989** [comment]
Could you explain what bugs, you have found as I am unable to see any issues from any of the code, that I have added, and the only issues are with the existing code, that my unit test has identified.

**Comment by Zunaira1989** [comment]
> Hi, I am checking your pull request. But I found there are some bugs in the code so it cannot be executed.
> 
> And also it seems that you have added quite a lot of new unit test cases. I don't know whether the test document is also required to be changed or not. Please discuss with Tolga as this may costs a lot of time.
> 
> In my opinion, I think it is enough to just update the function name in the previous program without adding new unit tests. If you are unsure, please do post your thought in the dicussion forum.

I have updated the unit test to account for encoding the pickle data to a string in the unit test, This no longer throws the exception on the decrypt_data

the second issue is still apparent but this is down the the simple_server code issue . 

please merge my PR when ready

**Comment by Zunaira1989** [comment]
Done

**Pull request merged**
